services:
  Frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: zpi/frontend
    container_name: ZPI_Frontend
    hostname: Frontend
    restart: unless-stopped
    ports:
      - 80:80
