services:
  Backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: nbp_crasher/backend
    container_name: NBP_Crasher_Backend
    hostname: Backend
    restart: unless-stopped
    ports:
      - 8000:8000