name: Backend Tests


on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'backend/**'
      - 'Backend/**'
  workflow_dispatch:

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  Test_Formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black pytest
          if [ -f ./backend/requirements.txt ]; then pip install -r ./backend/requirements.txt; fi


      - name: Lint with black
        run: |
          # Code formatting with black, check every python file in the src directory 
          black --check --diff backend

  Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [ -f ./backend/requirements.txt ]; then pip install -r ./backend/requirements.txt; fi


      - name: Test with pytest
        run: |
          pytest
